spring.application.name=product
server.port=8080
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Log4j2 properties
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.apogee=debug
logging.file.name=/application.log