spring.application.name=product
server.port=9090
spring.h2.console.enabled=true
#spring.datasource.url=$$SPRING_DATASOURCE_URL
spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Log4j2 properties
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.apogee=debug
logging.file.name=/application.log