#################################### Server Configurations  ####################################
spring.application.name=products-ms
server.port=9091
#################################### DB Configurations ##########################################
spring.datasource.url=jdbc:mysql://mysql-db:3306/products_db
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
####################################### Log4j2 properties  #######################################
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.apogee=debug
logging.file.name=/application.log